redhat-developer/rhosak-ui

- packages/ui/src/components/KafkaInstanceDrawer/components/CodeSnippets.ts
Few changes made to the springboot example snippets. We might need to make more changes till we get these snippets in the example codes and have the tests ready.
e might need to make more changes till we get these snippets in the example codes and have the tests ready.
> fix(code-snippets): changes to spring boot snippets

- apps/consoledot-rhosak/package.json
- package-lock.json
- package.json
change the app name to drop dashes; add a verify script
> chore: fixes for the containers based build

- package-lock.json
- packages/consoledot-api/package-lock.json
> Replace this with a quick explanation of what's included here. 
Delete the patternfly table module that was giving the checksum error, removed the node modules, and did a fresh npm install
> chore: fix the failing checksum

- packages/consoledot-api/package-lock.json
> Replace this with a quick explanation of what's included here. 
> update ui-components to latest version
> chore: update ui-components to latest version

- packages/consoledot-api/src/transformers/kafkaRequestToKafkaInstanceEnhanched.ts
Reverts redhat-developer/rhosak-ui#99
> chore: Revert "chore: initialize instance plan with the right data"

- packages/consoledot-api/src/transformers/kafkaRequestToKafkaInstanceEnhanched.ts
> Replace this with a quick explanation of what's included here. 
> Initialize the instance plan with the right data
> chore: initialize instance plan with the right data

- apps/consoledot-rhosak/src/routes/control-plane/routes/KafkaInstancesRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/DataPlaneHeaderConnected.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/DataPlaneTopicHeaderConnected.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/PermissionsSelectAccountRoute.tsx
- apps/consoledot-rhosak/src/useUserControlGate.tsx
- apps/consoledot-rhosak/src/utils.ts
- package-lock.json
- packages/consoledot-api/package.json
- packages/consoledot-api/src/queries/index.ts
- packages/consoledot-api/src/queries/useUser.ts
- packages/consoledot-api/src/queryKeys.ts
> chore: Bug fixes in the kafka instance table kabab menu

- apps/consoledot-rhosak/src/routes/control-plane/DrawerProvider.tsx
- packages/consoledot-api/src/queries/index.ts
- packages/consoledot-api/src/queries/useSSOProvider.ts
- packages/consoledot-api/src/queryKeys.ts
- packages/ui/src/components/KafkaInstanceDrawer/KafkaInstanceDrawer.tsx
- packages/ui/src/components/KafkaInstanceDrawer/components/KafkaConnectionTabP2.stories.tsx
- packages/ui/src/components/KafkaInstanceDrawer/components/KafkaConnectionTabP2.tsx
- packages/ui/src/components/KafkaInstanceDrawer/components/KafkaSampleCode.stories.tsx
- packages/ui/src/components/KafkaInstanceDrawer/components/KafkaSampleCode.tsx
- packages/ui/src/components/KafkaInstanceDrawer/components/kafkaConnectionTabP2.test.tsx
> implement token endpoint url
> chore: implement token endpoint url

- .github/workflows/pr.yml
- apps/consoledot-rhosak/fec.config.js
- apps/consoledot-rhosak/package.json
- apps/consoledot-rhosak/src/QuickstartLoader.tsx
- apps/consoledot-rhosak/src/routes/control-plane/ControlPlaneRoutes.tsx
- apps/consoledot-rhosak/src/routes/control-plane/routes/CreateKafkaInstanceRoute.tsx
- apps/consoledot-rhosak/src/routes/control-plane/routes/TermsAndConditionsRoute.tsx
- apps/consoledot-rhosak/src/routes/control-plane/routes/index.ts
- apps/consoledot-rhosak/src/routes/control-plane/routes/useSelfTermsReviewGate.tsx
- apps/consoledot-rhosak/src/routes/control-plane/routesConsts.ts
- apps/consoledot-rhosak/src/useUserControlGate.tsx
- package-lock.json
- packages/consoledot-api/package.json
- packages/consoledot-api/src/fetchers/fetchSelfTermsReview.ts
- packages/consoledot-api/src/fetchers/index.ts
- packages/consoledot-api/src/queries/index.ts
- packages/consoledot-api/src/queries/useSelfTermsReview.ts
- packages/consoledot-api/src/queries/useUser.ts
- packages/consoledot-api/src/queryKeys.ts
- packages/locales/en/terms-and-conditions.json
- packages/ui/src/components/I18nProvider.tsx
- packages/ui/src/components/TermsAndConditionsDialog/TermsAndConditionsDialog.stories.tsx
- packages/ui/src/components/TermsAndConditionsDialog/TermsAndConditionsDialog.tsx
- packages/ui/src/components/TermsAndConditionsDialog/index.ts
- packages/ui/src/components/index.ts
Checks the terms and conditions API to see if the user has accepted the T&S or if there is a new one to accept.
* Create a new user
* click on Create Kafka instance
* a dialog asking to accept the terms and condition should be displayed
> feat: add check for terms and condition when creating an instance

- apps/consoledot-rhosak/src/routes/data-plane/routes/ConsumerGroupDeleteRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/ConsumerGroupResetOffsetRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/TopicConsumerGroupDeleteRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/TopicConsumerGroupResetOffsetRoute.tsx
- apps/consoledot-rhosak/src/useAlerts.ts
>  Add alert for consumer group modal
> chore: Add alert for consumer group modal

- apps/consoledot-rhosak/src/routes/control-plane/routes/ChangeOwnerRoute.tsx
- apps/consoledot-rhosak/src/routes/control-plane/routes/DeleteKafkaInstanceRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/PermissionsEditRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/SettingsRoute.tsx
- apps/consoledot-rhosak/src/useAlerts.ts
> chore: Add alerts

- apps/consoledot-rhosak/src/routes/data-plane/routes/DashboardRoute.tsx
>Add link to create topic page in the metric Dashboard  
> chore: Add link to create topic page in the metric Dashboard 

- apps/consoledot-rhosak/src/routes/data-plane/routes/ConsumerGroupDeleteRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/ConsumerGroupResetOffsetRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/ConsumerGroupViewPartitionRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/ConsumerGroupsRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/PermissionsEditRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/TopicConsumerGroupDeleteRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/TopicConsumerGroupResetOffsetRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/TopicConsumerGroupViewPartitionRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/TopicConsumerGroupsRoute.tsx
- packages/consoledot-api/src/fetchers/fetchConsumerGroups.ts
- packages/consoledot-api/src/transformers/ConsumerGroupTransformer.ts
- packages/ui-models/src/models/consumer-group.ts
- packages/ui/src/components/ConsumerGroups/ConsumerGroups.stories.tsx
- packages/ui/src/components/ConsumerGroups/ConsumerGroups.test.tsx
- packages/ui/src/components/ConsumerGroups/ConsumerGroups.tsx
- packages/ui/src/hooks/useConsumerGroupLabels.ts
> chore: fix consumer group sort

- packages/ui/src/components/KafkaInstanceActions.tsx
>fix the kebab menu popup overlayed with the next Kafka instance 3dots menu
> chore: fix the kebab menu popup overlayed with next Kafka instance 3dots menu

- apps/consoledot-rhosak/src/routes/data-plane/routes/TopicDeleteRoute.tsx
- packages/ui/src/components/Settings/Settings.tsx
>Add alerts for delete topic
> Remove TODO for setting page, since the alert is added in the settingsRoute
> chore: bug fixes

- packages/ui/src/components/KafkaInstanceDrawer/KafkaInstanceDrawer.tsx
- packages/ui/src/components/KafkaInstanceDrawer/components/KafkaConnectionTabP2.tsx
> feat: Add link to the access tab

- packages/ui/src/components/KafkaInstanceDrawer/KafkaInstanceDrawer.tsx
- packages/ui/src/components/KafkaInstanceDrawer/components/KafkaConnectionTabP2.tsx
- packages/ui/src/components/KafkaInstanceDrawer/components/__snapshots__/kafkaConnectionTabP2.test.tsx.snap
I had the wrong links in place, this fixes it
> fix: correct link to the service accounts page

- packages/ui/src/components/Topic/components/CreateTopicWizard.tsx
> fix jumplinks not working in Advance Topic creation page 
> chore: fix jumplinks not working in Advance Topic creation page

- apps/consoledot-rhosak/src/routes/data-plane/routes/TopicCreateRoute.tsx
- apps/consoledot-rhosak/src/routes/data-plane/routes/TopicEditPropertiesRoute.tsx
- packages/ui/src/components/Topic/CreateTopic/CreateTopic.tsx
- packages/ui/src/components/Topic/EditTopicProperties/EditTopicProperties.tsx
- packages/ui/src/components/Topic/components/CreateTopicWizard.tsx
- packages/ui/src/components/Topic/components/TopicAdvancePage.tsx
- packages/ui/src/components/Topic/components/WizardCustomFooter.tsx
> Add a saving state in the topic creation and topic updation flow
> chore: Add saving state in the topic creation

- packages/ui/src/components/KafkaMessageBrowser/components/DateTimePicker.tsx
> fix Invalid time format error in the timestamp filter for message
fixes https://issues.redhat.com/browse/MGDX-293
> chore: fix Invalid time format error in the timestamp filter for message

- renovate.json
Attempt to enable Renovate Automerge
> chore: enable renovate automerge

- renovate.json
> Replace this with a quick explanation of what's included here. 
> chore: attempt to fix automerge again

- .github/workflows/pr.yml
Following the docs:
https://docs.renovatebot.com/key-concepts/automerge/#if-you-use-github-actions
> chore: Fix to enable automerge

- packages/ui/src/components/Topic/EditTopicProperties/EditTopicProperties.tsx
- packages/ui/src/components/Topic/components/CoreConfiguration.tsx
- packages/ui/src/components/Topic/components/CreateTopicWizard.tsx
- packages/ui/src/components/Topic/components/CustomRetentionMessage.tsx
- packages/ui/src/components/Topic/components/CustomRetentionSize.tsx
- packages/ui/src/components/Topic/components/StepMessageRetention.tsx
- packages/ui/src/components/Topic/components/TopicAdvancePage.tsx
- packages/ui/src/components/Topic/components/WizardCustomFooter.tsx
Add validation for retention time and size for topic creation(basic/advance) and topic edit
> chore: Add validation for retention size and time
